name: Build opus.lib on Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild environment
        uses: microsoft/setup-msbuild@v2

      - name: Configure Opus with CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DOPUS_STACK_PROTECTOR=OFF -DOPUS_HARDENING=OFF

      - name: Build Opus.lib
        run: |
          cmake --build build --config MinSizeRel --target opus

      - name: Upload opus.lib as artifact
        uses: actions/upload-artifact@v4
        with:
          name: opus-lib
          path: build/MinSizeRel/opus.lib
